version: '3.8'

services:
  mysql:
    image: mysql:latest
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      timeout: 20s
      retries: 10

    networks:
      custom_net:
        ipv4_address: 10.5.0.2
  
  llm-server:
    image: pimenvibritania/llm-server-python
    build: ./LLM
    environment:
      - SECRET_KEY=kmzway87aa
    volumes:
      - ./LLM/models:/app/models
    ports:
      - "5555:5555"
    networks:
      custom_net:
        ipv4_address: 10.5.0.3
  
  llm-api:
    image: pimenvibritania/llm-api-express
    build: ./API
    depends_on:
      mysql:
        condition: service_started
    environment:
      - DB_HOST=10.5.0.2
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=api_llama
      - LLM_HOST=10.5.0.3
      - LLM_PORT=5555
    ports:
      - "3000:3000"
    networks:
      custom_net:
        ipv4_address: 10.5.0.4

  init-migration:
    image: pimenvibritania/llm-api-express
    build: ./API
    command: npm run migrate:up
    volumes:
      - ./API/database.json:/app/database.json
      - mysql_data:/var/lib/mysql
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      custom_net:
        ipv4_address: 10.5.0.5

volumes:
  mysql_data:
    driver: local

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
